version: '3'
services:
  front-end:
    container_name: front-end
    build:
      context: NewLangUI
      dockerfile: Dockerfile
    image: front-end:latest
    ports:
      - 8081:8081
    depends_on:
      - back-end

  back-end:
    container_name: back-end
    build:
      context: NewLang
      dockerfile: Dockerfile
    image: back-end:latest
    ports:
      - 8080
