/*
 * This file was automatically generated by EvoSuite
 * Mon May 22 18:58:17 GMT 2023
 */

package evosuite_test;

import org.apache.commons.lang3.exception.ExceptionUtils;
import org.junit.jupiter.api.Test;
import static org.junit.Assert.*;
import compiler.symbolTable.RowTable;
import compiler.symbolTable.TypeField;
import org.junit.runner.RunWith;

public class RowTable_ESTest {

  @Test
  public void test00()  throws Throwable  {
      RowTable rowTable0 = new RowTable("", (Object) null, (TypeField) null, "");
      TypeField typeField0 = rowTable0.getType();
      assertNull(typeField0);
  }

  @Test
  public void test01()  throws Throwable  {
      Object object0 = new Object();
      TypeField.TypeFieldVar typeField_TypeFieldVar0 = new TypeField.TypeFieldVar("");
      RowTable rowTable0 = new RowTable("7exq~)12", object0, typeField_TypeFieldVar0, "e7c");
      String string0 = rowTable0.getSymbol();
      assertEquals("e7c", rowTable0.getPropreties());
      assertEquals("7exq~)12", string0);
  }

  @Test
  public void test02()  throws Throwable  {
      TypeField.TypeFieldFunction typeField_TypeFieldFunction0 = new TypeField.TypeFieldFunction();
      RowTable rowTable0 = new RowTable("", typeField_TypeFieldFunction0, typeField_TypeFieldFunction0, "");
      String string0 = rowTable0.getSymbol();
      assertEquals("", string0);
  }

  @Test
  public void test03()  throws Throwable  {
      TypeField.TypeFieldFunction typeField_TypeFieldFunction0 = new TypeField.TypeFieldFunction();
      RowTable rowTable0 = new RowTable("k{eO)U[ p%I]", typeField_TypeFieldFunction0, typeField_TypeFieldFunction0, (String) null);
      String string0 = rowTable0.getPropreties();
      assertNull(string0);
  }

  @Test
  public void test04()  throws Throwable  {
      TypeField.TypeFieldFunction typeField_TypeFieldFunction0 = new TypeField.TypeFieldFunction();
      Object object0 = new Object();
      RowTable rowTable0 = new RowTable("%ZZW4%&1xwt4u\u0003-", object0, typeField_TypeFieldFunction0, "");
      String string0 = rowTable0.getPropreties();
      assertEquals("", string0);
      assertEquals("%ZZW4%&1xwt4u\u0003-", rowTable0.getSymbol());
  }

  @Test
  public void test05()  throws Throwable  {
      RowTable rowTable0 = new RowTable("", (Object) null, (TypeField) null, "");
      Object object0 = rowTable0.getKind();
      assertNull(object0);
  }

  @Test
  public void test06()  throws Throwable  {
      RowTable rowTable0 = new RowTable("", "", (TypeField) null, "");
      // Undeclared exception!
      try { 
        rowTable0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
          String stacktrace = ExceptionUtils.getStackTrace(e);
          assertTrue(stacktrace.contains("compiler.symbolTable.RowTable"));
      }
  }

  @Test
  public void test07()  throws Throwable  {
      TypeField.TypeFieldFunction typeField_TypeFieldFunction0 = new TypeField.TypeFieldFunction();
      RowTable rowTable0 = new RowTable("7exq~)12", typeField_TypeFieldFunction0, typeField_TypeFieldFunction0, "");
      rowTable0.toString();
      assertEquals("7exq~)12", rowTable0.getSymbol());
      assertEquals("", rowTable0.getPropreties());
  }

  @Test
  public void test08()  throws Throwable  {
      Object object0 = new Object();
      TypeField.TypeFieldVar typeField_TypeFieldVar0 = new TypeField.TypeFieldVar("");
      RowTable rowTable0 = new RowTable("7exq~)12", object0, typeField_TypeFieldVar0, "e7c");
      rowTable0.toString();
      assertEquals("7exq~)12", rowTable0.getSymbol());
      assertEquals("e7c", rowTable0.getPropreties());
  }

  @Test
  public void test09()  throws Throwable  {
      Object object0 = new Object();
      TypeField.TypeFieldVar typeField_TypeFieldVar0 = new TypeField.TypeFieldVar("");
      RowTable rowTable0 = new RowTable("7exq~)12", object0, typeField_TypeFieldVar0, "e7c");
      rowTable0.getType();
      assertEquals("e7c", rowTable0.getPropreties());
      assertEquals("7exq~)12", rowTable0.getSymbol());
  }

  @Test
  public void test10()  throws Throwable  {
      TypeField.TypeFieldFunction typeField_TypeFieldFunction0 = new TypeField.TypeFieldFunction();
      Object object0 = new Object();
      RowTable rowTable0 = new RowTable((String) null, object0, typeField_TypeFieldFunction0, "TB");
      String string0 = rowTable0.getPropreties();
      assertEquals("TB", string0);
  }

  @Test
  public void test11()  throws Throwable  {
      TypeField.TypeFieldFunction typeField_TypeFieldFunction0 = new TypeField.TypeFieldFunction();
      Object object0 = new Object();
      RowTable rowTable0 = new RowTable((String) null, object0, typeField_TypeFieldFunction0, "TB");
      String string0 = rowTable0.getSymbol();
      assertNull(string0);
  }

  @Test
  public void test12()  throws Throwable  {
      Object object0 = new Object();
      TypeField.TypeFieldVar typeField_TypeFieldVar0 = new TypeField.TypeFieldVar("");
      RowTable rowTable0 = new RowTable("7exq~)12", object0, typeField_TypeFieldVar0, "e7c");
      rowTable0.getKind();
      assertEquals("e7c", rowTable0.getPropreties());
      assertEquals("7exq~)12", rowTable0.getSymbol());
  }
}
